### PR TITLE
add docker db instructions

### PR DESCRIPTION
**Pull request by EvanGertis**

### CODE REVIEW

**Comment by EvanGertis** [comment]
This PR is an update to add instructions to our README.

**Comment by EvanGertis** [comment]
[add local docker database](https://trello.com/c/mtgUCj54/18-add-local-docker-database)

**Review by blister — CHANGES_REQUESTED** [review]
This is in the `public` folder, which, by default, is served by Express.

Anyone can view this README file when your server is running.

**Review by EvanGertis — COMMENTED** [review]
changes reviewed

**Pull request merged**
